[project]
name = "practical-deep-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "ddgs>=9.16.0",
    "fastai>=2.0.0,<2.8",
    "fastdownload>=0.0.8",
    "numpy<2",
]

[dependency-groups]
dev = ["ipykernel>=7.3.0", "ruff>=0.16.8"]

[tool.ruff]
line-length = 100

[tool.uv]
required-environments = [
    "sys_platform == 'darwin' and platform_machine == 'x86_64'",
]
